export const productlistdata = [
  {
    id: 1,
    product: "Malakand",
    productImage: "assets/img/products/stock-img-01.png",
    sku: "PT001",
    category: "Laptop",
    brand: "Lenovo",
    price: "$12500.00",
    unit: "Pc",
    qty: "100",
    createdby: "Arroon",
    img: "assets/img/users/user-30.jpg",
  },
  {
    id: 2,
    product: "Hazara",
    productImage: "assets/img/products/stock-img-06.png",
    sku: "PT002",
    category: "Electronics",
    brand: "Bolt",
    price: "$1600.00",
    unit: "Pc",
    qty: "140",
    createdby: "Kenneth",
    img: "assets/img/users/user-13.jpg",
  },
  {
    id: 3,
    product: "Karachi",
    productImage: "assets/img/products/stock-img-02.png",
    sku: "PT003",
    category: "Shoe",
    brand: "Nike",
    price: "$6000.00",
    unit: "Pc",
    qty: "780",
    createdby: "Gooch",
    img: "assets/img/users/user-11.jpg",
  },
  
];
